### ISSUE TITLE
Women In Tech Meetup - [12/2/2022] 

### ISSUE THREAD

**Issue by techie-maria** [techie-maria/LinkedIn-Planning#22]
### **Meetup Information**

* Name: Women in Tech
* Location:  1191 Rue Saint-Jean Quebec City, Quebec G1R 1S3 Canada
* Date: 12/2/2023
* Time:10AM-4PM UTC-4
* Estimated number of attendees: 150
* Description: This Women Tech meetup is hosted to celebrate and highlight voices of those who identify as women in the tech field with highlighted lightening talks. This year we are aiming to hold a hybrid event where participants can join virtually and others can be present at the event venue. 

### **What help is needed**
- [x] Organizers
- [ ] Volunteers
- [x] Mentor
### Discussed in https://github.com/techie-maria/LinkedIn-Planning/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **howiecadell** August 11, 2022</sup>
More events needed to populate tracker, please link relevant events through this discussion to help out. </div>

**Comment by freyaterray** [comment]
I'll be available that day and would love to help out!  How can I become invovled?
